### ISSUE TITLE
pilot cmd results in bad lexical cast

### ISSUE THREAD

**Issue by jzaturensky** [airmap/platform-sdk#118]
**Describe the bug**

When running ./airmap pilot:

{“hostname”:“MacBook-Pro-2.local”,“level”:50,“msg”:“error while running the context: bad lexical cast: source type value could not be interpreted as target”,“name”:“airmap::boost::Context”,“pid”:35758,“time”:“2018-09-04T23:09:08.980868Z”,“v”:0}

Issue seems to originate from the following function:
airmap::iso8601::generate()

**To Reproduce**
1. Run the pilot cmd

**Comment by vosst** [comment]
@jzaturensky mind producing a backtrace with:
```
gdb --args ./airmap pilot
# in the gdb prompt
catch throw
run
```

**Comment by jzaturensky** [comment]
@vosst Just ran a clean build with docker Ubuntu 18.04 and seems like it is running fine now - may be just an issue with my macOS environment
