### ISSUE TITLE
Another segfault on Linux

### ISSUE THREAD

**Issue by bartslinger** [airmap/platform-sdk#133]
My operating system is Ubuntu 18.04. I compiled QGC master @e1a290be2 including AirMap. AirMap is compiled using the instructions on https://github.com/airmap/platform-sdk, with qt-support enabled. I copied the libairmap-qt.so* files to `qgroundcontrol/libs/airmapd/linux/Qt.5.11.0`.

If I don't enter an API key, QGC does not crash. When I enter an API key, I get a segfault. If I disable the function `AirMapRulesetsManager::setROI`, QGC does not crash.

This is what I see in the debugger:
![](https://i.imgur.com/th9uMNQ.png)

**Comment by dogmaphobic** [comment]
You only copied the binaries? You would need to build QGC with the same set of header files you used to build airmapd.

**Comment by dogmaphobic** [comment]
Again, with that said, only macOS is known to work.

**Comment by bartslinger** [comment]
I assumed headers should be the same for macOS and Linux. There are no linking issues.

I still have two questions regarding this:
1) Is this problem related to the SDK, or QGC?
2) When can we expect airmap+QGC integration working on Linux?

**Comment by bartslinger** [comment]
I'll give that a shot on Monday, thanks.

**Comment by bartslinger** [comment]
That seems to work, although I'm not getting weather information at the moment. Thanks for your help.
