### ISSUE TITLE
Provide a deb package for aarch64 at version 2.0

### ISSUE THREAD

**Issue by petronny** [airmap/platform-sdk#182]
**Is your feature request related to a problem? Please describe.**
Hi, currently qgroundcontrol needs the prebuilt deb package at version 2.0 to build on x86_64.
However, for building qgroundcontrol on aarch64, there is no airmap-platform-sdk-2.0-aarch64.deb.
Therefore the airmap support could not be enabled in qgroundcontrol on aarch64.

**Describe the solution you'd like**
Please provide a deb package for aarch64 at version 2.0 for building qgroundcontrol with airmap support on aarch64.

**Describe alternatives you've considered**
Well, or update the code of qgroundcontrol to work with airmap 2.1.0 which already has a package for aarch64.

**Additional context**
We can manage to change the url here to build on aarch64.
https://github.com/mavlink/qgroundcontrol/blob/master/QGCExternalLibs.pri#L299

**Comment by remster** [comment]
@petronny - FYI: started addressing it https://github.com/mavlink/qgroundcontrol/pull/10394 - still draft

**Comment by remster** [comment]
Found one problem that Android's arm clang raised that our arm build did not. I am not sure whether this is difference in compilers or simply exercising the code (class actually subclassed). In the meantime I need this nit approved @petronny: https://github.com/airmap/platform-sdk/pull/185

**Comment by remster** [comment]
@petronny can you confirm that you need the `aarch64` binary because you're building for Android? Or is it something else?

**Comment by petronny** [comment]
I'm building qgroundcontrol for ArchLinuxARM aarch64.
Somebody contacts me and requests this package for aarch64.

Here is the related issue: https://github.com/acxz/pkgbuilds/issues/201

**Comment by remster** [comment]
So [this](https://github.com/mavlink/qgroundcontrol) much has been done. I have published the `[airmap-platform-sdk-2.0.1-Linux-aarch64.deb](https://github.com/airmap/platform-sdk/releases/download/2.0.1/airmap-platform-sdk-2.0.1-Linux-aarch64.deb)` artifact, but [QGC doesn't link for Android](https://github.com/mavlink/qgroundcontrol/runs/8257871762?check_suite_focus=true). I don't know why yet and this requires some digging. Is it because the Android linker isn't given the binaries, or the binaries aren't what it expects. The aarch64 artifacts platform-sdk publishes are based on NVIDIA Jetson L4T and do not know enough of it to be certain the architecture versions match. I **think** it should be v8 64. 
Now, you @petronny aren't interested in building Android - so maybe you can do your bit on the QGC side and check if yours link and do so on top of [this](https://github.com/mavlink/qgroundcontrol/pull/10394) PR. I hope this helps.

**Comment by remster** [comment]
@petronny ? Is this not helpful or you've got distracted?

**Comment by petronny** [comment]
Sorry I was busy about something else. I will give it a try tomorrow.

**Comment by petronny** [comment]
In https://github.com/mavlink/qgroundcontrol/pull/10394, the following part
```
        AIRMAP_PLATFORM_SDK_ARCH = ""
        LinuxBuild {
            AIRMAP_PLATFORM_SDK_ARCH = "x86_64"
        } else:AndroidBuild {
            AIRMAP_PLATFORM_SDK_ARCH = "aarch64"
        }
```
doesn't work on aarch64 linux. It is still a linux build so AIRMAP_PLATFORM_SDK_ARCH is set to "x86_64".

However, if AIRMAP_PLATFORM_SDK_ARCH is forced to be "aarch64", then qgroundcontrol can be built on aarch64 with airmap-platform-sdk-2.0.1-Linux-aarch64.deb.

**Comment by remster** [comment]
Ok @petronny [this](https://github.com/mavlink/qgroundcontrol/pull/10394) is how far i went. I haven't got an arm linux at hand, so i must ask you to help me test my PR and comment on it as to what you did so that we convince the QGC code owners to merge it. If you can approve it, please do.

**Comment by petronny** [comment]
With the latest code, l find 
```
Project MESSAGE: Skipping support for Airmap (unsupported architecture)
``` in the outputs. 

Is there a way to show the value of `QT_ARCH` on my system?

**Comment by remster** [comment]
there you go: https://github.com/mavlink/qgroundcontrol/pull/10394/commits/1282bf6c6e94bb21ed2a93da94cec3c297589d65

**Comment by petronny** [comment]
This time it works fine.

**Comment by remster** [comment]
FYI: https://px4.slack.com/archives/C629RE9H7/p1664378094337889 i am trying to get the attention of the QGC moderators, but i haven't got an approving review. You may want to poke them too.

**Comment by dayjaby** [comment]
Please please please don't delete old release versions. Releases are supposed to be stable and part of the definition of stable is that it remains accessible. Otherwise, this breaks any kind of CI:

E.g. this step is part of QGroundControl failed now for me:
```runner/_work/_temp/shadow_build_dir/airmap-platform-sdk.deb https://github.com/airmap/platform-sdk/releases/download/2.0/airmap-platform-sdk-2.0.0-Linux.deb && ar p /home/david/actions-runner/_work/_temp/shadow_build_dir/airmap-platform-sdk.deb data.tar.gz | tar xvz -C ```

**Comment by remster** [comment]
@dayjaby - terribly sorry - we've learnt that on github, removing (renaming) a tag removes the release associated with that tag. We didn't connect the dots and ended up breaking our own builds. Now all should be back to normal. Once again, our apologies.

**Comment by dayjaby** [comment]
Thanks for your quick response. Will test it right away 👍

**Comment by remster** [comment]
https://github.com/mavlink/qgroundcontrol/pull/10394 merged

**Comment by farhangnaderi** [comment]
Hello, 
I was wondering if there is any update regarding Android for this?
